[Deploy] Some script updates (Recidiviz/recidiviz-data#15126)
* Add messages to start / end of deploy

* Verify psycopg2 and Python major/minor version

* Use `get_secret` function where applicable

`psycopg2` installed successfully despite runtime errors being raised on import, as the C bindings were misconfigured.
This was being raised during @daschi's last deploy:
```python
>  ImportError: dlopen(/Users/daschi/.local/share/virtualenvs/recidiviz-data-deploy-V1J5hE1I/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): Library not loaded: '/usr/lib/libpq.5.dylib'
>    Referenced from: '/Users/daschi/.local/share/virtualenvs/recidiviz-data-deploy-V1J5hE1I/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so'
>    Reason: tried: '/usr/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file)
```

When using Python 3.8, some scripts fail to parse due to native types not being subscriptable (added in 3.9) i.e. `dict[str, str]` versus `typing.Dict[str, str]`.
```python
>  Traceback (most recent call last):
>    File "/Users/daschi/.pyenv/versions/3.8.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>      return _run_code(code, main_globals, None,
>    File "/Users/daschi/.pyenv/versions/3.8.8/lib/python3.8/runpy.py", line 87, in _run_code
>      exec(code, run_globals)
>    File "/Users/daschi/Desktop/Recidiviz/recidiviz-data-deploy/recidiviz/tools/migrations/run_migrations_to_head.py", line 48, in <module>
>      from recidiviz.tools.migrations.migration_helpers import (
>    File "/Users/daschi/Desktop/Recidiviz/recidiviz-data-deploy/recidiviz/tools/migrations/migration_helpers.py", line 75, in <module>
>      class EngineIteratorDelegate(abc.ABC):
>    File "/Users/daschi/Desktop/Recidiviz/recidiviz-data-deploy/recidiviz/tools/migrations/migration_helpers.py", line 88, in EngineIteratorDelegate
>      ) -> dict[str, Optional[str]]:
>  TypeError: 'type' object is not subscriptable
```

GitOrigin-RevId: 2cdae456084e285d5315fe3a27ffebaff0159fb1