Only recycle postgres connections for 10 minutes (Recidiviz/recidiviz-data#3818)
We have been seeing the following error in production recently:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
We have especially noticed that this happens at time of low load, e.g. when Anna just attempted to kick off PA in staging with nothing else running.

Google docs show that CloudSQL connections from Compute Engine that have been stale from more than 10 minutes will be closed. Given that AppEngine flex is really just compute engine under the hood this likely applies to us as well.

It also would make sense that these errors have increased recently, given that we increased the minimum number of instances and therefore have more idle workers and connections lying around at times of low load.

SQLAlchemy says that pool_recycle is the way to get around this.

Co-authored-by: Anna Geiduschek <anna@recidiviz.org>
GitOrigin-RevId: f473ef45b790f62f567c1b57a187da81287ff076