[BQ materialization] Exclude metadata columns from results batch query (Recidiviz/recidiviz-data#12723)
While running BQ materialization ingest in secondary for our first state (!!), hit this crash during the `/direct/extract_and_merge` step:

```
ValueError: Found columns in input results row [0] not present in manifest |input_columns| list: {'__materialization_time', '__upper_bound_datetime_inclusive', '__lower_bound_datetime_exclusive', '__processed_time', '__extract_and_merge_batch'}
```
This fixes to exclude those columns from our SELECT query so that the parser does not attempt to parse them.

Related to Recidiviz/recidiviz-data#9717.

GitOrigin-RevId: 9ae95de247b2cccea19ce63ea3ff3b0e3ef24f93