[BQ materialization] Fixes to maintain consistency ingest view file values (Recidiviz/recidiviz-data#12842)
Seeing two different ingest crashes related to the fact that the values we're reading from BQ are not exactly in the same format as the values we used to read from ingest view files.

1) Emtpy values used to be read as empty strings, but now we're getting `None` values from our BQ results. This is resulting in this crash in MO where we're expecting all nonnull values in legacy mappings code:
```
  File "/app/recidiviz/ingest/extractor/csv_data_extractor.py", line 441, in _get_creation_args
    child_primary_key_coords = self._child_primary_coordinates(
  File "/app/recidiviz/ingest/extractor/csv_data_extractor.py", line 411, in _child_primary_coordinates
    child_primary_key_value = self._build_dummy_child_primary_key(
  File "/app/recidiviz/ingest/extractor/csv_data_extractor.py", line 402, in _build_dummy_child_primary_key
    return "|".join(child_primary_key_parts)
TypeError: sequence item 4: expected str instance, NoneType found
```

2) I missed `date` as a format to convert to string, so an ingest view in ME that is producing date columns is crashing:
```
  File "/app/recidiviz/big_query/big_query_results_contents_handle.py", line 60, in get_contents_iterator
    yield {key: self.value_converter(key, row.get(key)) for key in row.keys()}
  File "/app/recidiviz/big_query/big_query_results_contents_handle.py", line 60, in <dictcomp>
    yield {key: self.value_converter(key, row.get(key)) for key in row.keys()}
  File "/app/recidiviz/ingest/direct/ingest_view_materialization/instance_ingest_view_contents.py", line 144, in to_string_value_converter
    raise ValueError(f"Unexpected value type [{type(value)}]: {value}")
ValueError: Unexpected value type [<class 'datetime.date'>]: 2007-10-02
```

Related to Recidiviz/recidiviz-data#9717

GitOrigin-RevId: 08be291b93f0cd16da3b86d60c4ccad872275f92