Revert "Add TN to Terraform config lists (Recidiviz/recidiviz-data#5653)" (Recidiviz/recidiviz-data#5817)
This reverts commit dca5975acff1c13b26c3dd1c1615a435ec4e51cb.

It looks like in Recidiviz/recidiviz-data#5745 when we made the config for the prod-only upload-testing bucket, we failed to gate creation of the cloud function that references that bucket to prod-only as well.

Terraform apply is failing with this error:
```
Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Cloud Storage trigger bucket recidiviz-staging-direct-ingest-state-us-tn-upload-testing not found

```

(I think we made the MO buckets manually in prod and staging which is why this is happening only now?)

GitOrigin-RevId: 6755b19b1828e2331514e665b819075906e023aa