[Tooling] Throw in load_views_to_sandbox if input views/datasets do not exist (Recidiviz/recidiviz-data#14304)
Slight refactor to the `load_views_to_sandbox` script to make it throw if you try to run it with an input view or dataset that does not exist.

These calls both now will fail:
```
python -m recidiviz.tools.load_views_to_sandbox --project_id recidiviz-staging --sandbox_dataset_prefix ageiduschek --dataset_ids_to_load foo --update_descendants True
python -m recidiviz.tools.load_views_to_sandbox --project_id recidiviz-staging --sandbox_dataset_prefix ageiduschek --dataset_ids_to_load sessions,foo --update_descendants True
```
... with this error:
```
ValueError: Did not find any views in the following datasets: {'foo'}
```

And these calls will both now fail:
```
python -m recidiviz.tools.load_views_to_sandbox --project_id recidiviz-staging --sandbox_dataset_prefix ageiduschek --view_ids_to_load sessions.foo --update_descendants True
python -m recidiviz.tools.load_views_to_sandbox --project_id recidiviz-staging --sandbox_dataset_prefix ageiduschek --view_ids_to_load sessions.dataflow_sessions,sessions.foo --update_descendants True
```

... with this error:
```
ValueError: Expected to find [1], but only found [0] that matched managed views. Did not find views that matched the following expected addresses: {BigQueryAddress(dataset_id='sessions', table_id='foo')}.
```
GitOrigin-RevId: caf5bd82f9316beed981b45e36f114d1e7b006b7