[US_CO] Add missing StatePerson ethnicity mapping (Recidiviz/recidiviz-data#12771)
Fix this CO ingest crash in staging:
```
  File "/app/recidiviz/ingest/direct/direct_ingest_control.py", line 637, in process_job
    controller.run_extract_and_merge_job_and_kick_scheduler_on_completion(
  File "/app/recidiviz/ingest/direct/controllers/base_direct_ingest_controller.py", line 703, in run_extract_and_merge_job_and_kick_scheduler_on_completion
    should_schedule = self._run_extract_and_merge_job(args)
  File "/app/recidiviz/ingest/direct/controllers/base_direct_ingest_controller.py", line 775, in _run_extract_and_merge_job
    self._parse_and_persist_contents(args, contents_handle)
  File "/app/recidiviz/utils/trace.py", line 79, in run_inside_new_span
    return func(*args, **kwargs)
  File "/app/recidiviz/ingest/direct/controllers/base_direct_ingest_controller.py", line 845, in _parse_and_persist_contents
    persist_success = processor.parse_and_persist_contents(
  File "/app/recidiviz/ingest/direct/controllers/ingest_view_processor.py", line 85, in parse_and_persist_contents
    parsed_entities = self.ingest_view_file_parser.parse(
  File "/app/recidiviz/ingest/direct/ingest_mappings/ingest_view_results_parser.py", line 65, in parse
    output_tree = output_manifest.build_from_row(row)
  File "/app/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 183, in build_from_row
    field_value = field_manifest.build_from_row(row)
  File "/app/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 621, in build_from_row
    child_entity = child_manifest.build_from_row(row)
  File "/app/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 183, in build_from_row
    field_value = field_manifest.build_from_row(row)
  File "/app/recidiviz/ingest/direct/ingest_mappings/ingest_view_manifest.py", line 783, in build_from_row
    return StrictEnumParser(
  File "/app/recidiviz/common/constants/strict_enum_parser.py", line 59, in parse
    raise EnumParsingError(self.enum_cls, self.raw_text)
recidiviz.common.constants.enum_parser.EnumParsingError: Could not parse U when building <aenum 'StateEthnicity'>
```

GitOrigin-RevId: 166bea4af29479423404ee5b1f1c0df666c0ebd6